### ISSUE TITLE
Criar um icone para organização

### ISSUE THREAD

**Issue by pedropolisenso** [Atomic-Design/patterns#3]
Sem mais, apenas criar um icone legal 

CC: @Atomic-Design/owners @Atomic-Design/devs

**Comment by pedropolisenso** [comment]
Sugestão: http://goo.gl/PWv1Ay

**Comment by suissa** [comment]
Acho uma boa em amarelo e verde hehehhehe

**Comment by pedropolisenso** [comment]
Boa @suissa vai dar um destaque para nós, devs brasileiros. O que importa mesmo é começarmos a trabalhar em cima dessa metodologia e padronizar, para que pessoas usem algo padronizado por nós, saca?

PS: Verde e amarelo não é ruim mesmo não rss!

**Comment by suissa** [comment]
Essa é a ideia

**Comment by erickjones** [comment]
![atomic-design-logo](https://cloud.githubusercontent.com/assets/1272620/6145741/49e09338-b1cc-11e4-99c7-e2e3f998480f.png)

**Comment by pedropolisenso** [comment]
Perfeito @erickjones :+1:

**Comment by erickjones** [comment]
Só uma idéia. Parece o http://patternlab.io/ do Brad Frost, mas podemos fazer sem ser redondo também, pra quebrar o paradigma.

**Comment by pedropolisenso** [comment]
Parece porque esse símbolo ja é uma referência para Atomic Design, e acredito não gerar problemas algum.

**Comment by suissa** [comment]
Exatamente o q eu pensei @erickjones

**Comment by pedropolisenso** [comment]
@suissa já pode colocar esse icone como perfil aqui da organização né seu prego rss =)

**Comment by suissa** [comment]
Feito

**Comment by pedropolisenso** [comment]
:+1:
